version: '3'
services:
  '7.1': &base
    image: "circleci/php:7.1"
    ulimits:
      core: 99999999999
    working_dir: '/home/circleci/app'
    stdin_open: true
    tty: true
    volumes: [ '.:/home/circleci/app' ]
    depends_on:
      - redis_integration
      - ddagent_integration
    environment:
      - REDIS_HOSTNAME=redis_integration
      - DDAGENT_HOSTNAME=ddagent_integration
  '5.6':
    <<: *base
    image: "circleci/php:5.6"
  redis_integration:
    image: "circleci/redis:4.0-alpine"
  ddagent_integration:
    image: datadog/agent:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "HEAD", "http://localhost:8126"]
      interval: 10s
      timeout: 2s
      retries: 2
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=5fa68aae23e4822d6f778f8d163f85e8
    ports:
      - "8126:8126"
