version: 2.0

aliases:
  - &CACHE_COMPOSER_KEY
    key: 'betav1-composer-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}'

  - &CACHE_NPM_KEY
    key: 'betav1-lint-deps-{{ checksum "composer.json" }}'

  - &IMAGE_DOCKER_DD_AGENT
    image: datadog/docker-dd-agent
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=invalid_key_but_this_is_fine

  - &STEP_EXT_INSTALL
    run:
      name: Build and install extension
      command: make -f DDMakefile install install_ini SUDO=sudo BUILD_DIR=tmp/build_extension

  - &STEP_COMPOSER_SELF_UPDATE
    run:
      name: Updating composer itself
      command: sudo composer self-update

  - &STEP_COMPOSER_CACHE_RESTORE
    restore_cache:
      <<: *CACHE_COMPOSER_KEY

  - &STEP_COMPOSER_CACHE_SAVE
    save_cache:
      <<: *CACHE_COMPOSER_KEY
      paths:
        - vendor/

  - &STEP_COMPOSER_INSTALL
    run:
      name: Installing dependencies with composer
      command: composer install -n

  - &STEP_STORE_ARTIFACTS
    store_artifacts:
      path: test-results

  - &STEP_STORE_TEST_RESULTS
    store_test_results:
      path: test-results

  - &JOB_PHP_DEFAULTS
    working_directory: ~/datadog
    steps:
      - checkout
      - attach_workspace:
          at: ~/datadog
      - <<: *STEP_EXT_INSTALL
      - run:
          name: Waiting for Dockerized agent
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m
      - run:
          name: Run unit tests
          command: composer test-unit -- --log-junit test-results/php-unit/results.xml
      - run:
          name: Run integration tests
          command: composer test-integration -- --log-junit test-results/php-integration/results.xml
      - <<: *STEP_STORE_TEST_RESULTS
      - <<: *STEP_STORE_ARTIFACTS

jobs:
  "Lint files":
    docker:
      - image: circleci/php:7-cli-node-browsers
    steps:
      - checkout
      - <<: *STEP_EXT_INSTALL
      - <<: *STEP_COMPOSER_SELF_UPDATE
      - <<: *STEP_COMPOSER_CACHE_RESTORE
      - <<: *STEP_COMPOSER_INSTALL
      - <<: *STEP_COMPOSER_CACHE_SAVE
      - restore_cache:
          <<: *CACHE_NPM_KEY
      - run:
          name: Installing dependencies with npm
          command: npm install eclint --no-package-lock --no-save
      - save_cache:
          <<: *CACHE_NPM_KEY
          paths:
          - node_modules/
      - run:
          name: Creating directory for phpcs results
          command: mkdir -p test-results/phpcs
      - run:
          name: Running eclint
          command: node_modules/.bin/eclint check '**/*' '!tmp/**/*' '!vendor/**/*' '!src/ext/.libs/*' '!LICENSE' '!phpstan.neon'
      - run:
          name: Running phpcs
          command: composer lint -- --report=junit | tee test-results/phpcs/results.xml
      - run:
          name: Install clang-format 6.0
          command: sudo apt -y install clang-format-6.0/testing
      - run:
          name: Run clang-format
          command: |
            find ./ -iname *.h -o -iname *.c | while read fname; do
              changes=$(clang-format-6.0 -output-replacements-xml $fname | grep -c "<replacement " || true)
              if [ $changes != 0 ]
              then
                clang-format-6.0 -output-replacements-xml $fname
                echo "$fname did not pass clang-format, consider running: find ./ -iname *.h -o -iname *.c | xargs clang-format -i"
                exit 1
              fi
            done
      - <<: *STEP_STORE_TEST_RESULTS
      - <<: *STEP_STORE_ARTIFACTS

  "Static Analysis":
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - <<: *STEP_EXT_INSTALL
      - <<: *STEP_COMPOSER_SELF_UPDATE
      - <<: *STEP_COMPOSER_CACHE_RESTORE
      - <<: *STEP_COMPOSER_INSTALL
      - <<: *STEP_COMPOSER_CACHE_SAVE
      - run:
          name: Installing phpstan
          command: composer require --dev phpstan/phpstan:~0.10.3
      - run:
          name: Running phpstan
          command: vendor/bin/phpstan analyse --level=2 src

  "build 5.6": &BASE_BUILD
    working_directory: ~/datadog
    docker:
      - image: circleci/php:5.6
    steps:
      - checkout
      - <<: *STEP_EXT_INSTALL
      - <<: *STEP_COMPOSER_SELF_UPDATE
      - <<: *STEP_COMPOSER_CACHE_RESTORE
      - <<: *STEP_COMPOSER_INSTALL
      - <<: *STEP_COMPOSER_CACHE_SAVE
      - run:
          name: testresults dir
          command: mkdir test-results
      - run:
          name: Run extension tests
          command: TEST_PHP_JUNIT=test-results/simle_test.xml REPORT_EXIT_STATUS=1 make -f DDMakefile test_c
      - run:
          name: Install VALGRIND(todo build custom image)
          command: sudo apt update && sudo apt install valgrind -y
      - run:
          name: Run extension tests with leak detection
          command: TEST_PHP_JUNIT=test-results/leak_test.xml REPORT_EXIT_STATUS=1 make -f DDMakefile test_c_mem
      - persist_to_workspace:
          root: '.'
          paths:
            - vendor/
            - tmp/build_extension
      - <<: *STEP_STORE_TEST_RESULTS
      - <<: *STEP_STORE_ARTIFACTS

  "build 7.0":
    <<: *BASE_BUILD
    docker: [ image: 'circleci/php:7.0' ]

  "build 7.1":
    <<: *BASE_BUILD
    docker: [ image: 'circleci/php:7.1' ]

  "build 7.2":
    <<: *BASE_BUILD
    docker: [ image: 'circleci/php:7.2' ]

  "php-5.6":
    <<: *JOB_PHP_DEFAULTS
    docker:
      - image: 'circleci/php:5.6'
      - <<: *IMAGE_DOCKER_DD_AGENT

  "php-7.0":
    <<: *JOB_PHP_DEFAULTS
    docker:
      - image: circleci/php:7.0
      - <<: *IMAGE_DOCKER_DD_AGENT

  "php-7.1":
    <<: *JOB_PHP_DEFAULTS
    docker:
      - image: circleci/php:7.1
      - <<: *IMAGE_DOCKER_DD_AGENT

  "php-7.2":
    <<: *JOB_PHP_DEFAULTS
    docker:
      - image: circleci/php:7.2
      - <<: *IMAGE_DOCKER_DD_AGENT

workflows:
  version: 2
  build:
    jobs:
      - "Lint files"
      - "Static Analysis"
      - "build 5.6"
      - "build 7.0"
      - "build 7.1"
      - "build 7.2"
      - "php-5.6": { requires: [ "build 5.6" ] }
      - "php-7.0": { requires: [ "build 7.0" ] }
      - "php-7.1": { requires: [ "build 7.1" ] }
      - "php-7.2": { requires: [ "build 7.2" ] }
